### ISSUE TITLE
The old lua cannot be used.

### ISSUE THREAD

**Issue by diszids** [beihu235/NovaFlare-Engine-V1.1.0-oldBase#3]
### Describe your problem here.

When I used my lua, I found that it was no longer running.
Can you provide the latest lua tutorial?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by beihu235** [comment]
uhhhhh 
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7

**Comment by diszids** [comment]
> 嗯嗯 https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7

thank you
