### ISSUE TITLE
Upload notes

### ISSUE THREAD

**Issue by Guillermo4060** [beihu235/NovaFlare-Engine-V1.1.0-oldBase#5]
### What feature do you want to get added on the **base** engine?

I would like to or well, an idea is that I don't know if you can rehabilitate the old way that the arrow skins loaded since now it is more complicated when loading and in many mods they have errors in that, like this mod below and I would like If in the future or if it can be fixed or rehabilitated it would fix many errors of psych engine 0.7.1h
![Screenshot_20231004-234655](https://github.com/beihu235/NF-Engine-new/assets/100426962/8308f452-8f32-4692-9a94-9ec00d7485c2)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by beihu235** [comment]
it fixed, check StrumNote.hx and Note.hx,then use mine Path.hx,it is update for android

**Comment by beihu235** [comment]
it fixed,check StrumNote.hx,Note.hx and VisualsUISubState.hx,then use my version of Path.hx,it update for android a lot
