### ISSUE TITLE
Lua fix

### ISSUE THREAD

**Issue by Guillermo4060** [beihu235/NovaFlare-Engine-V1.1.0-oldBase#6]
### What feature do you want to get added on the **base** engine?

Hello, the error in the notes was fixed but I have detected that in many mods and even in new ones, the lua of the events fails and cannot be repaired, so I propose if perhaps you can put it back to handle the old lua codes and the new ones now What have I seen that right now they are different in the codes so that the psych engine 0.7.1h improves a lot in that section :)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by beihu235** [comment]
I've been working on it, and it should fix everything except runhaxecode

**Comment by Guillermo4060** [comment]
Ohh it's okay because some mods have bugs in the lua and in the mechanics that's why

**Comment by beihu235** [comment]
idk,but almost problem from runhaxecode,0.63h is use hscript,but 0.71h is use SScript,so some lua will not work,and get or setPropertyFromclass need put its path
